node:
  DataInputNode:
    output:
      out: DATA

  DataOutputNode:
    input:
      in: DATA

  ObjectInputNode:
    output:
      out: OBJECT

  ObjectOutputNode:
    input:
      in: OBJECT

  ObjectUniNode:
    input:
      in: OBJECT
    output:
      out: OBJECT

  ObjectBiNode:
    input:
      in1: OBJECT
      in2: OBJECT
    output:
      out1: OBJECT
      out2: OBJECT

  MeasureNode:
    input:
      in: OBJECT
    output:
      out: OBJECT
      value: DATA
model:
  station:
    station1:
      - ObjectInputNode
      - ObjectOutputNode
    station2:
      - ObjectUniNode
      - MeasureNode
    station3:
      - ObjectUniNode
    station4:
      - ObjectBiNode
    station5:
      - ObjectBiNode